# Generated by Django 6.0.6 on 2026-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Organization')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact submission',
                'verbose_name_plural': 'Contact submissions',
                'db_table': 'contact_submissions',
                'ordering': ('-submitted_at',),
            },
        ),
    ]
